### ISSUE TITLE
Migrating CAIRIS GUI to CAIRIS web

### ISSUE THREAD

**Issue by failys** [failys/cairis#36]
While much of the CAIRIS GUI is available in the CAIRIS web app, this issue keeps track of the various tasks that need to be complete before the web app (and web services API) is functionality complete.

When we've ticked off all these boxes, we can say that the core of 'CAIRIS Web' is functionally complete.

# Absent interfaces
- [x] Domain Properties
- [x] Obstacles
- [x] Personas
- [x] Tasks
- [x] Use Cases
- [x] Countermeasures
- [x] Goal Associations 
- [x] Class Associations 
- [x] Responsibility Associations
- [x] Responsibility models
- [x] Persona Argumentation models
- [x] Searching by text / type
- [x] Model export
- [x] Documentation generation

# Absent web services
- [x] Domain Properties
- [x] Obstacles
- [x] Personas
- [x] Tasks
- [x] Countermeasures
- [x] Use Cases
- [x] Goal Associations 
- [x] Class Associations 
- [x] Responsibility Associations
- [x] Documentation generation

# Incomplete models

## Asset model
- [x] Asset security property values not displayed
- [x] Persona values not displayed
- [x] model filtering

## Risk model
- [x] Asset security properties not visible
- [x] Asset security property options not displayed
- [x] Threat likelihood not visible
- [x] Threat security properties not visible
- [x] Vulnerabilities severity not visible
- [x] Roles not properly displayed
- [x] Task values not displayed
- [x] Attacker values not displayed
- [x] Threat values not displayed
- [x] Vulnerability values not displayed
- [x] Risk values not displayed
- [x] Misuse case values not displayed
- [x] Role values not displayed
- [x] Response values not displayed
- [x] Obstacle values not displayed
- [x] Requirement values not displayed
- [x] Countermeasure values not displayed
- [x] model filtering

## KAOS models
- [x] Goal options not displayed
- [x] Obstacle options not displayed
- [x] Role options not displayed
- [x] Domain property options not displayed
- [x] model filtering

## Task model
- [x] Task values not displayed
- [x] Misuse case values not displayed
- [x] Role values not displayed
- [x] Persona values not displayed
- [x] Attacker values not displayed
- [x] model filtering

**Comment by failys** [comment]
Response properties visible in web app risk model

**Comment by failys** [comment]
Duplicate entries in list

**Comment by failys** [comment]
Duplicate entries

**Comment by failys** [comment]
Duplicates
